name: "UFW-Addon"
description: "UFW add-on!"
version: "1.0.2"
slug: "ufw_addon"
init: false
privileged: true
network: host
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  libmodules: /lib/modules
