name: "UFW-Addon"
description: "UFW add-on!"
version: "1.0.3"
slug: "ufw_addon"
init: false
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
